### ISSUE TITLE
Get "": unsupported protocol scheme ""

### ISSUE THREAD

**Issue by alexshaoo** [evanhyd/MeowyPlayer#7]
seems like a go net/http issue, seems to happen only sometimes, i'll see if i can reproduce it consistently further down the line

**Comment by evanhyd** [comment]
If a YouTube video gets taken down, the download URL will be empty as Y2Mate can no longer find the music resources. Some of the music from the public server got copyright strikes by the Youtube police, unfortunately.

While testing the downloading feature, I also found a deadlock related to SyncMusic() function. I need some time to investigate it more.

**Comment by evanhyd** [comment]
The issue has been resolved in version 2.3
